# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  prime: swagger/schema/prime.yaml
  support: swagger/schema/support.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  htmlTemplate: swagger/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
  # NOTE: modifying most theme attributes won't work here - use Redoc.init for standalone instead
