version: '3.3'

services:
   database:
     image: postgres:10.9
     restart: always
     environment:
       PGPASSWORD: mysecretpassword

   milmove_migrate:
     depends_on:
       - database
     image: 923914045601.dkr.ecr.us-west-2.amazonaws.com/app-migrations:git-branch-cg_docker_compose
     ports:
       - '5436:5432'
     environment:
       - DB_ENV=development
       - DB_HOST=database
       - DB_NAME
       - DB_PASSWORD
       - DB_PORT
       - DB_USER
       - ENVIRONMENT=test
       - SECURE_MIGRATION_DIR
       - SECURE_MIGRATION_SOURCE

   milmove:
     depends_on:
       - database
       - milmove_migrate
     image: 923914045601.dkr.ecr.us-west-2.amazonaws.com/app:git-branch-cg_docker_compose
     ports:
       - '5000:5000'
     environment:
       - CLIENT_AUTH_SECRET_KEY
       - CSRF_AUTH_KEY
       - DB_ENV=development
       - DB_HOST=database
       - DB_NAME
       - DB_PASSWORD
       - DB_PORT=5436
       - DB_USER
       - DEVLOCAL_CA=/config/tls/devlocal-ca.pem
       - DEVLOCAL_AUTH=true
       - DOD_CA_PACKAGE=/config/tls/Certificates_PKCS7_v5.4_DoD.der.p7b
       - DPS_AUTH_COOKIE_SECRET_KEY
       - DPS_COOKIE_EXPIRES_IN_MINUTES
       - ENVIRONMENT=test
       - HERE_MAPS_APP_CODE
       - HERE_MAPS_APP_ID
       - HERE_MAPS_GEOCODE_ENDPOINT
       - HERE_MAPS_ROUTING_ENDPOINT
       - HTTP_MY_SERVER_NAME=milmovelocal
       - HTTP_OFFICE_SERVER_NAME=officelocal
       - HTTP_TSP_SERVER_NAME=tsplocal
       - HTTP_ADMIN_SERVER_NAME=adminlocal
       - HTTP_ORDERS_SERVER_NAME=orderslocal
       - IWS_RBS_HOST
       - LOGIN_GOV_CALLBACK_PORT=5000
       - LOGIN_GOV_CALLBACK_PROTOCOL
       - LOGIN_GOV_HOSTNAME
       - LOGIN_GOV_MY_CLIENT_ID
       - LOGIN_GOV_OFFICE_CLIENT_ID
       - LOGIN_GOV_SECRET_KEY
       - LOGIN_GOV_TSP_CLIENT_ID
       - LOGIN_GOV_ADMIN_CLIENT_ID
       - MOVE_MIL_DOD_CA_CERT
       - MOVE_MIL_DOD_TLS_CERT
       - MOVE_MIL_DOD_TLS_KEY
       - NO_TLS_ENABLED=1
       - NO_TLS_PORT=5000
       - SECURE_MIGRATION_DIR
       - SECURE_MIGRATION_SOURCE
       - STORAGE_BACKEND=memory
