version: '3.3'

services:
  database:
    image: postgres:10.9
    restart: always
    ports:
      - '6432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=dev_db
  server_test:
    image: trussworks/circleci-docker-primary:e5c10bf19185aa55354901106bad3ffd4c016265
    links:
      - database
    volumes:
      - /Users/john/projects/dod/milmove:/home/circleci/transcomm/mymove
    environment:
      - CIRCLECI=1
      - DB_ENV=development
      - DB_HOST=database
      - DB_NAME=dev_db
      - DB_NAME_TEST=test_db
      - DB_PASSWORD=mysecretpassword
      - PGPASSWORD=mysecretpassword
      - DB_PORT=5432
      - DB_PORT_TEST=5432
      - DB_SSL_MODE=disable
      - DB_USER=postgres
      - DEVLOCAL_CA=/config/tls/devlocal-ca.pem
      - DEVLOCAL_AUTH=true
      - ENVIRONMENT=test
      - STORAGE_BACKEND=local
      - SERVE_ADMIN=true
      - SERVE_API_INTERNAL=true
      - SERVE_API_PUBLIC=true
    command: bash -c "cd /home/circleci/transcomm/mymove && ./scripts/run_server_test_in_circle_container"
