swagger: '2.0'
info:
  description: The API for move.mil admin actions.
  version: 1.0.0
  title: move.mil Admin API
  license:
    name: MIT
    url: 'https://github.com/transcom/mymove/blob/master/LICENSE.md'
basePath: /admin/api/v1
