swagger: '2.0'
info:
  description: The public API for my.move.mil. This is a work in-progress, and is not a final product. We will be continuously updating this site based on feedback.
  version: 0.0.1
  title: my.move.mil
  license:
    name: MIT
    url: https://github.com/transcom/mymove/blob/master/LICENSE.md
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
definitions:
  TSP:
    type: object
    description: The primary definition of a Transport Service Provider
    properties:
      id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      name:
        type: string
        example: Moving Company, Inc.
        minLength: 1
        maxLength: 1024
      scac:
        type: string
        description: The SCAC associated with the TSP
        format: '^[A-Z]{2,4}$'
        example: USPS
      contact_email:
        type: string
        format: x-email
        pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        example: john_bob@example.com
  StorageInTransit:
    type: object
    properties:
      id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      location:
        type: string
        title: SIT Location
        enum:
          - ORIGIN
          - DESTINATION
        x-display-value:
          ORIGIN: Origin
          DESTINATION: Destination
      estimated_start_date:
        type: string
        format: date
        example: '2018-04-26'
        title: Estimated start date
      authorized_start_date:
        type: string
        format: date
        x-nullable: true
        example: '2018-04-26'
        title: Authorized Start Date
      actual_start_date:
        type: string
        format: date
        x-nullable: true
        example: '2018-04-26'
        title: Actual Start Date
      out_date:
        type: string
        format: date
        x-nullable: true
        example: '2018-04-26'
        title: Out Date
      notes:
        type: string
        example: Good to go!
        format: textarea
        x-nullable: true
        title: Note
      authorization_notes:
        type: string
        example: Good to go!
        format: textarea
        x-nullable: true
        title: Authorization Notes
      warehouse_id:
        type: string
        example: '000383'
        title: Warehouse ID number
      warehouse_name:
        type: string
        example: ABC Warehouse, Inc.
        title: Warehouse Name
      warehouse_phone:
        type: string
        format: telephone
        pattern: '^$|^[2-9]\d{2}-\d{3}-\d{4}$'
        example: 212-555-5555
        x-nullable: true
        title: Phone
      warehouse_email:
        type: string
        format: x-email
        pattern: '^$|^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        example: john_bob@example.com
        x-nullable: true
        title: Email
      shipment_id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
        title: Shipment ID
      sit_number:
        type: string
        x-nullable: true
        example: 123456
        title: SIT Number
      status:
        type: string
        example: REQUESTED
        title: Status
    required:
      - location
      - warehouse_id
      - warehouse_name
      - estimated_start_date
  StorageInTransits:
    type: array
    items:
      $ref: '#/definitions/StorageInTransit'
  StorageInTransitApprovalPayload:
    type: object
    properties:
      authorization_notes:
        type: string
        format: textarea
        example: Good to go!
        title: Authorization Notes
        x-nullable: true
      authorized_start_date:
        type: string
        format: date
        example: '2018-04-26'
        title: Authorized Start Date
  StorageInTransitDenialPayload:
    type: object
    properties:
      authorization_notes:
        type: string
        format: textarea
        example: Good to go!
        title: Authorization Notes
  StorageInTransitInSitPayload:
    type: object
    properties:
      actual_start_date:
        type: string
        format: date
        example: '2018-04-26'
        title: Actual Start date
  StorageInTransitReleasePayload:
    type: object
    properties:
      released_on:
        type: string
        format: date
        example: '2018-04-26'
        title: Released On Date

paths:
  /shipments/{shipmentId}/storage_in_transits:
    get:
      summary: Gets storage in transit entries for shipment
      description: Allows a user to retrieve a list of storage in transit entires for a shipment.
      operationId: indexStorageInTransits
      tags:
        - storage_in_transits
      parameters:
        - name: shipmentId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of shipment
      responses:
        200:
          description: returns an array of storage in transit entires
          schema:
            $ref: '#/definitions/StorageInTransits'
        400:
          description: invalid request
        401:
          description: must be authenticated to use this end point
        403:
          description: not authorized to list these storage in transit entries
        422:
          description: cannot process request with given information
        500:
          description: server error
    post:
      summary: Create a storage in transit entry
      description: Creates a new storage in transit entry associated with a shipment
      operationId: createStorageInTransit
      tags:
        - storage_in_transits
      parameters:
        - name: shipmentId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of the shipment
        - name: storageInTransit
          in: body
          required: true
          description: Storage In Transit information
          schema:
            $ref: '#/definitions/StorageInTransit'
      responses:
        201:
          description: successfully created Storage In Transit
          schema:
            $ref: '#/definitions/StorageInTransit'
        400:
          description: invalid request
        401:
          description: must be authenticated to use this end point
        403:
          description: not authorized to add transit in storage entires to this shipment
        500:
          description: server error
  /shipments/{shipmentId}/storage_in_transits/{storageInTransitId}:
    get:
      summary: Gets a particular Storage In Transit for a shipment
      description: Allows a user to retrieve a specific Storage In Transit entry for a shipment
      operationId: getStorageInTransit
      tags:
        - storage_in_transits
      parameters:
        - name: shipmentId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of the shipment
        - name: storageInTransitId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of the Storage in Transit entry
      responses:
        200:
          description: returns the details of a storage in transit entry
          schema:
            $ref: '#/definitions/StorageInTransit'
        400:
          description: invalid request
        401:
          description: must be authenticated to use this endpoint
        403:
          description: not authorized to view the details of this storage in transit entry
        404:
          description: storage in transit UUID not found in system
        500:
          description: server error
    patch:
      summary: Updates an particular Storage In Transit entry
      description: Allows changes to be made to a particular Storage In Transit entry
      operationId: patchStorageInTransit
      tags:
        - storage_in_transits
      parameters:
        - name: shipmentId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of shipment
        - name: storageInTransitId
          in: path
          type: string
          format: uuid
          description: UUID of storage in transit
          required: true
        - name: storageInTransit
          in: body
          required: true
          schema:
            $ref: '#/definitions/StorageInTransit'
      responses:
        200:
          description: returns the details of the storage in transit entry
          schema:
            $ref: '#/definitions/StorageInTransit'
        400:
          description: invalid request
        401:
          description: must be authenticated to use this endpoint
        403:
          description: not authorized to update the details of this service agent
        404:
          description: storage in transit UUID not found in system
        500:
          description: server error
    delete:
      summary: Deletes a particular Storage In Transit entry related to a shipment
      operationId: deleteStorageInTransit
      tags:
        - storage_in_transits
      parameters:
        - name: shipmentId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of shipment
        - name: storageInTransitId
          in: path
          type: string
          format: uuid
          description: UUID of storage in transit
          required: true
      responses:
        200:
          description: the storage in transit entry was successfully deleted
          schema:
            $ref: '#/definitions/StorageInTransit'
        400:
          description: invalid request
        401:
          description: must be authenticated to use this endpoint
        403:
          description: not authorized to access the associated storage in transit entry
        404:
          description: no service agent found with that UUID
        500:
          description: server error
  /shipments/{shipmentId}/storage_in_transits/{storageInTransitId}/approve:
    post:
      summary: Approves a requested storage in transit
      operationId: approveStorageInTransit
      tags:
        - storage_in_transits
      parameters:
        - name: shipmentId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of shipment
        - name: storageInTransitId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of storage in transit
        - in: body
          name: storageInTransitApprovalPayload
          required: true
          schema:
            $ref: '#/definitions/StorageInTransitApprovalPayload'
      responses:
        200:
          description: returns storage in transit that was approved
          schema:
            $ref: '#/definitions/StorageInTransit'
        400:
          description: invalid request
        401:
          description: must be authenticated to use this endpoint
        403:
          description: not authorized to approve this storage in transit
        409:
          description: the storage in transit is not in an appropriate state to be approved
          schema:
            $ref: '#/definitions/StorageInTransit'
        500:
          description: server error
  /shipments/{shipmentId}/storage_in_transits/{storageInTransitId}/deny:
    post:
      summary: Denies a requested storage in transit
      operationId: denyStorageInTransit
      tags:
        - storage_in_transits
      parameters:
        - name: shipmentId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of shipment
        - name: storageInTransitId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of storage in transit
        - in: body
          name: storageInTransitDenyPayload
          required: true
          schema:
            $ref: '#/definitions/StorageInTransitDenialPayload'
      responses:
        200:
          description: returns storage in transit that was denied
          schema:
            $ref: '#/definitions/StorageInTransit'
        400:
          description: invalid request
        401:
          description: must be authenticated to use this endpoint
        403:
          description: not authorized to deny this storage in transit
          schema:
            $ref: '#/definitions/StorageInTransit'
        409:
          description: the storage in transit is not in an appropriate state to be approved
        500:
          description: server error
  /shipments/{shipmentId}/storage_in_transits/{storageInTransitId}/place_in_sit:
    post:
      summary: Places a storage in transit into 'IN_SIT'
      operationId: inSitStorageInTransit
      tags:
        - storage_in_transits
      parameters:
        - name: shipmentId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of shipment
        - name: storageInTransitId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of storage in transit
        - name: storageInTransitInSitPayload
          in: body
          schema:
            $ref: '#/definitions/StorageInTransitInSitPayload'
      responses:
        200:
          description: returns storage in transit that was put into in_sit
          schema:
            $ref: '#/definitions/StorageInTransit'
        400:
          description: invalid request
        401:
          description: must be authenticated to use this endpoint
        403:
          description: not authorized to in_sit this storage in transit
        409:
          description: the storage in transit is not in an appropriate state to be put in_sit
          schema:
            $ref: '#/definitions/StorageInTransit'
        500:
          description: server error
  /shipments/{shipmentId}/storage_in_transits/{storageInTransitId}/release:
    post:
      summary: Releases a requested storage in transit
      operationId: releaseStorageInTransit
      tags:
        - storage_in_transits
      parameters:
        - name: shipmentId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of shipment
        - name: storageInTransitId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of storage in transit
        - name: storageInTransitOnReleasePayload
          in: body
          schema:
            $ref: '#/definitions/StorageInTransitReleasePayload'
      responses:
        200:
          description: returns storage in transit that was released
          schema:
            $ref: '#/definitions/StorageInTransit'
        400:
          description: invalid request
        401:
          description: must be authenticated to use this endpoint
        403:
          description: not authorized to release this storage in transit
        409:
          description: the storage in transit is not in an appropriate state to be released
          schema:
            $ref: '#/definitions/StorageInTransit'
        500:
          description: server error
  /shipments/{shipmentId}/storage_in_transits/{storageInTransitId}/deliver:
    post:
      summary: Delivers a requested storage in transit
      operationId: deliverStorageInTransit
      tags:
        - storage_in_transits
      parameters:
        - name: shipmentId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of shipment
        - name: storageInTransitId
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of storage in transit
      responses:
        200:
          description: returns storage in transit that was delivered
          schema:
            $ref: '#/definitions/StorageInTransit'
        400:
          description: invalid request
        401:
          description: must be authenticated to use this endpoint
        403:
          description: not authorized to deliver this storage in transit
        409:
          description: the storage in transit is not in an appropriate state to be delivered
          schema:
            $ref: '#/definitions/StorageInTransit'
        500:
          description: server error
  /tsps:
    get:
      summary: List all TSPs
      description: Gets a list of all the TSPs which the logged in user has access to.
      operationId: indexTSPs
      tags:
        - tsps
      x-access: Access to this endpoint is restricted to members of the Admin, Transcom & JPPSO user groups
      responses:
        200:
          description: list of TSPs
          schema:
            type: array
            items:
              $ref: '#/definitions/TSP'
        400:
          description: invalid request
        401:
          description: must be authenticated to access this endpoint
        500:
          description: server error
