swagger: '2.0'
info:
  description: The public API for my.move.mil. This is a work in-progress, and is not a final product. We will be continuously updating this site based on feedback.
  version: 0.0.1
  title: my.move.mil
  license:
    name: MIT
    url: https://github.com/transcom/mymove/blob/master/LICENSE.md
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
definitions:
  TSP:
    type: object
    description: The primary definition of a Transport Service Provider
    properties:
      id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      name:
        type: string
        example: Moving Company, Inc.
        minLength: 1
        maxLength: 1024
      scac:
        type: string
        description: The SCAC associated with the TSP
        format: '^[A-Z]{2,4}$'
        example: USPS
      contact_email:
        type: string
        format: x-email
        pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        example: john_bob@example.com
  AccessCode:
    type: object
    properties:
      id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      service_member_id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      code:
        type: string
        example: CODE456
      move_type:
        type: string
        title: Selected Move Type
        enum:
          - HHG
          - PPM
      created_at:
        type: string
        format: datetime
        example: 2018-04-12T23:20:50.52Z
        description: when the access code was created
      claimed_at:
        type: string
        format: datetime
        example: 2018-04-12T23:20:50.52Z
        description: when the access code was claimed or used
        x-nullable: true
    required:
      - id
      - code
      - move_type
      - created_at
paths:
  /tsps:
    get:
      summary: List all TSPs
      description: Gets a list of all the TSPs which the logged in user has access to.
      operationId: indexTSPs
      tags:
        - tsps
      x-access: Access to this endpoint is restricted to members of the Admin, Transcom & JPPSO user groups
      responses:
        200:
          description: list of TSPs
          schema:
            type: array
            items:
              $ref: '#/definitions/TSP'
        400:
          description: invalid request
        401:
          description: must be authenticated to access this endpoint
        500:
          description: server error
  /access_codes:
    get:
      summary: Fetches an access code
      description: Fetches the access code for a service member.
      operationId: fetchAccessCode
      tags:
        - accesscode
      responses:
        200:
          description: access code has been found in system
          schema:
            $ref: '#/definitions/AccessCode'
        400:
          description: invalid request
        401:
          description: not authorized to fetch access code
        404:
          description: access code not found in system
        500:
          description: server error
  /access_codes/valid:
    get:
      summary: Validate if an access code has been unused and associated with the correct move type.
      description: Verifies if access code is both unused and correctly associated with a move type.
      operationId: validateAccessCode
      tags:
        - accesscode
      parameters:
        - in: query
          name: code
          type: string
          description: the code the access code represents and verifies if in use
          pattern: '^(HHG|PPM)-[A-Z0-9]{6}$'
          x-nullable: false
      responses:
        200:
          description: access code is invalid or valid
          schema:
            $ref: '#/definitions/AccessCode'
        400:
          description: invalid request
        401:
          description: not authorized to validate access code
        404:
          description: access code not found in system
        500:
          description: server error
  /access_codes/invalid:
    patch:
      summary: Updates access code as invalid by associating it with the current service member.
      description: Updates access code as invalid by associating it with the current service member.
      operationId: claimAccessCode
      tags:
        - accesscode
      parameters:
        - in: body
          name: accessCode
          description: the code the access code represents and verifies if in use
          required: true
          schema:
            type: object
            required:
              - code
            properties:
              code:
                type: string
      responses:
        200:
          description: access code is invalid or valid
          schema:
            $ref: '#/definitions/AccessCode'
        400:
          description: invalid request
        401:
          description: not authorized to validate access code
        404:
          description: access code not found in system
        500:
          description: server error
