version: 2
jobs:

  pre_deps_golang:
    working_directory: ~/go/src/github.com/transcom/mymove
    docker:
      - image: trussworks/circleci-docker-primary:b6b61600e0a99745194eb8bfcab1c9bc1e54c28d
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-pkg-dep-sources-{{ checksum "Gopkg.lock" }}
      - restore_cache:
          keys:
            - mymove-vendor-{{ checksum "Gopkg.lock" }}
      - run:
          name: Install dependencies
          command: dep ensure -vendor-only
      - save_cache:
          key: go-pkg-dep-sources-{{ checksum "Gopkg.lock" }}
          paths:
            - ~/go/pkg/dep/sources
      - save_cache:
          key: mymove-vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - ~/go/src/github.com/transcom/mymove/vendor
      - run: &announce_failure
          name: Announce failure
          command: |
            [[ $CIRCLE_BRANCH = master ]] || exit 0
            bin/circleci-announce-broken-branch
          when: on_fail

  pre_deps_yarn:
    working_directory: ~/go/src/github.com/transcom/mymove
    docker:
      - image: trussworks/circleci-docker-primary:b6b61600e0a99745194eb8bfcab1c9bc1e54c28d
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-node-modules-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install YARN dependencies
          command: yarn install
      - save_cache:
          key: yarn-node-modules-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: *announce_failure

  pre_test:
    working_directory: ~/go/src/github.com/transcom/mymove
    docker:
      - image: trussworks/circleci-docker-primary:b6b61600e0a99745194eb8bfcab1c9bc1e54c28d
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-pkg-dep-sources-{{ checksum "Gopkg.lock" }}
      - restore_cache:
          keys:
            - mymove-vendor-{{ checksum "Gopkg.lock" }}
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Install prettier
          command: npm install prettier@~1.12.0
      - run:
          name: Install markdown-spellcheck
          command: npm install markdown-spellcheck
      - run:
          name: Install markdown-toc
          command: npm install markdown-toc
      - run: echo 'export PATH=${PATH}:~/go/bin' >> $BASH_ENV
      - run:
          name: Run make server_generate
          command: make server_generate
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
      - run: *announce_failure

  integration_tests:
    working_directory: ~/go/src/github.com/transcom/mymove
    docker:
      - image: trussworks/circleci-docker-primary:b57cdd9fd4b61d85f49134bf76c16961670f0257
      - image: postgres:10-alpine
        environment:
          - POSTGRES_PASSWORD: mysecretpassword
          - POSTGRES_DB: test_db
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-go-pkg-dep-{{ checksum "Gopkg.lock" }}
            - v1-go-pkg-dep
            - client-deps-cache-{{ checksum "yarn.lock" }}

      - run:
          # This is needed to use `psql` to test DB connectivity, until the app
          # itself starts making database connections.
          name: Install postgres client
          command: |
            sudo apt-get -qq update
            sudo apt-get -qq -y install postgresql-client-9.6
      - run:
          name: Cypress deps
          command: |
            sudo apt-get -qq -y install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
      - run:
          name: Install cypress
          command: npm install cypress@~3.1.0
      - run:
          name: Setup hostnames
          command: |
            echo 127.0.0.1 officelocal | sudo tee -a /etc/hosts
            echo 127.0.0.1 tsplocal | sudo tee -a /etc/hosts
      - run:
          name: make e2e_test_ci
          command: |
            echo 'export HTTPS_CERT=$(cat /home/circleci/go/src/github.com/transcom/mymove/config/tls/devlocal-https.pem)' >> $BASH_ENV
            echo 'export HTTPS_KEY=$(cat /home/circleci/go/src/github.com/transcom/mymove/config/tls/devlocal-https.key)' >> $BASH_ENV
            echo 'export HTTPS_CLIENT_AUTH_CA_CERT=$(cat /home/circleci/go/src/github.com/transcom/mymove/config/tls/devlocal-ca.pem)' >> $BASH_ENV
            echo 'export CLIENT_AUTH_SECRET_KEY=$(cat /home/circleci/go/src/github.com/transcom/mymove/config/tls/devlocal-client_auth_secret.key)' >> $BASH_ENV
            echo 'export LOGIN_GOV_SECRET_KEY=$(echo $E2E_LOGIN_GOV_SECRET_KEY | base64 --decode)' >> $BASH_ENV
            echo 'export LOGIN_GOV_HOSTNAME=$E2E_LOGIN_GOV_HOSTNAME' >> $BASH_ENV
            echo 'export HERE_MAPS_APP_ID=$E2E_HERE_MAPS_APP_ID' >> $BASH_ENV
            echo 'export HERE_MAPS_APP_CODE=$E2E_HERE_MAPS_APP_CODE' >> $BASH_ENV
            source $BASH_ENV
            make e2e_test_ci
          environment:
              # Env vars needed by the `bin/apply-secure-migrations.sh` script
              DB_PASSWORD: mysecretpassword
              DB_USER: postgres
              DB_HOST: localhost
              DB_PORT: 5432
              DB_NAME: test_db
              # Env vars needed for the webserver to run
              SECURE_MIGRATION_DIR: /home/circleci/go/src/github.com/transcom/mymove/local_migrations
              SECURE_MIGRATION_SOURCE: local
              LOGIN_GOV_CALLBACK_PROTOCOL: http://
              LOGIN_GOV_MY_CLIENT_ID: urn:gov:gsa:openidconnect.profiles:sp:sso:dod:mymovemillocal
              LOGIN_GOV_OFFICE_CLIENT_ID: urn:gov:gsa:openidconnect.profiles:sp:sso:dod:officemovemillocal
              LOGIN_GOV_TSP_CLIENT_ID: urn:gov:gsa:openidconnect.profiles:sp:sso:dod:tspmovemillocal
              LOGIN_GOV_HOSTNAME: idp.int.identitysandbox.gov
              HERE_MAPS_GEOCODE_ENDPOINT: https://geocoder.cit.api.here.com/6.2/geocode.json
              HERE_MAPS_ROUTING_ENDPOINT: https://route.cit.api.here.com/routing/7.2/calculateroute.json
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - store_test_results:
          path: cypress/results

      - save_cache:
          key: v1-go-pkg-dep-{{ checksum "Gopkg.lock" }}
          paths:
            - ~/go/pkg/dep
      - save_cache:
          key: client-deps-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
      - run: *announce_failure

  vuln_scan:
    working_directory: ~/go/src/github.com/transcom/mymove
    docker:
      - image: trussworks/circleci-docker-primary:b6b61600e0a99745194eb8bfcab1c9bc1e54c28d
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-pkg-dep-sources-{{ checksum "Gopkg.lock" }}
      - restore_cache:
          keys:
            - mymove-vendor-{{ checksum "Gopkg.lock" }}
      - restore_cache:
          keys:
            - yarn-node-modules-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Authenticate with Snyk
          command: npx snyk auth $SNYK_API_TOKEN
      - run:
          name: Add Go binaries to path
          command: echo 'export PATH=${PATH}:~/go/bin' >> $BASH_ENV
      - run:
          name: Run make server_generate
          command: make server_generate
      - run:
          name: Scan JavaScript dependencies for known vulnerabilities
          command: npx snyk test --file=package.json || exit 0
      - run:
          name: Scan Go dependencies for known vulnerabilities
          command: npx snyk test --file=Gopkg.lock || exit 0 # needs to run after server_generate, so gen files exist
      - run: *announce_failure

  build_app:
    working_directory: ~/go/src/github.com/transcom/mymove
    docker:
      - image: trussworks/circleci-docker-primary:b6b61600e0a99745194eb8bfcab1c9bc1e54c28d
      - image: postgres:latest
        environment:
          - POSTGRES_PASSWORD: mysecretpassword
          - POSTGRES_DB: test_db
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - go-pkg-dep-sources-{{ checksum "Gopkg.lock" }}
      - restore_cache:
          keys:
            - mymove-vendor-{{ checksum "Gopkg.lock" }}
      - restore_cache:
          keys:
            - yarn-node-modules-cache-{{ checksum "yarn.lock" }}

      - run:
          # This is needed to use `psql` to test DB connectivity, until the app
          # itself starts making database connections.
          name: Install postgres client
          command: |
            sudo apt-get -qq update
            sudo apt-get -qq -y install postgresql-client-9.6

      - run: echo 'export PATH=${PATH}:~/go/bin' >> $BASH_ENV
      - run: make deps
      - run: make client_build
      - run: make client_test
      - run:
          name: make server_test
          command: make server_test
          environment:
            # Env vars needed by the `bin/apply-secure-migrations.sh` script
            DB_PASSWORD: mysecretpassword
            DB_USER: postgres
            DB_HOST: localhost
            DB_PORT: 5432
            DB_NAME: test_db
            SECURE_MIGRATION_DIR: /home/circleci/go/src/github.com/transcom/mymove/local_migrations
            SECURE_MIGRATION_SOURCE: local
      - run: make tools_build
      - run: make server_build_docker
      - run:
          name: Tag and push image
          command: |
            bash -c "$(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)"
            docker tag ppp:web-dev ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app:git-${CIRCLE_SHA1}
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app:git-${CIRCLE_SHA1}

      - run: *announce_failure

  build_migrations:
    docker:
      - image: trussworks/circleci-docker-primary:b6b61600e0a99745194eb8bfcab1c9bc1e54c28d
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make db_build_docker
      - run:
          name: Tag and push migrations image
          command: |
            bash -c "$(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)"
            docker tag ppp-migrations:dev ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-migrations:git-${CIRCLE_SHA1}
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-migrations:git-${CIRCLE_SHA1}
      - run: *announce_failure

  deploy_experimental_migrations:
    docker:
      - image: trussworks/circleci-docker-primary:b6b61600e0a99745194eb8bfcab1c9bc1e54c28d
    environment:
      - APP_ENVIRONMENT: "experimental"
    steps: &deploy_migrations_steps
      - checkout
      - run:
          name: Snapshot database
          command: bin/rds-snapshot-app-db $APP_ENVIRONMENT
      - run:
          name: Run database migrations
          command: bin/ecs-run-app-migrations-container config/app-migrations.container-definition.json ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-migrations:git-${CIRCLE_SHA1} $APP_ENVIRONMENT
      - run: *announce_failure

  deploy_experimental_app:
    docker:
      - image: trussworks/circleci-docker-primary:b6b61600e0a99745194eb8bfcab1c9bc1e54c28d
    environment:
      - APP_ENVIRONMENT: "experimental"
      - APP_HEALTH_CHECK_URL: "https://my.experimental.move.mil/health"
    steps: &deploy_app_steps
      - checkout
      - setup_remote_docker
      - deploy:
          name: Deploy app service
          command: bin/ecs-deploy-service-container app config/app.container-definition.json ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app:git-${CIRCLE_SHA1} $APP_ENVIRONMENT FARGATE
      - run:
          name: Health check app site
          command: for retry in `seq 1 10`; do if curl -f -sS -o /dev/null $APP_HEALTH_CHECK_URL; then echo Passed.; exit 0; else sleep $(($retry*3)); fi; done; exit 1
      - run: *announce_failure

  deploy_experimental_app_client_tls:
    docker:
      - image: trussworks/circleci-docker-primary:b57cdd9fd4b61d85f49134bf76c16961670f0257
    environment:
      - APP_ENVIRONMENT: "experimental"
    steps: &deploy_app_client_tls_steps
      - checkout
      - setup_remote_docker
      - deploy:
          name: Deploy app-client-tls service
          command: bin/ecs-deploy-service-container app-client-tls config/app-client-tls.container-definition.json ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app:git-${CIRCLE_SHA1} $APP_ENVIRONMENT FARGATE
      - run: *announce_failure

  deploy_staging_migrations:
    docker:
      - image: trussworks/circleci-docker-primary:b57cdd9fd4b61d85f49134bf76c16961670f0257
    environment:
      - APP_ENVIRONMENT: "staging"
    steps: *deploy_migrations_steps

  deploy_staging_app:
    docker:
      - image: trussworks/circleci-docker-primary:b57cdd9fd4b61d85f49134bf76c16961670f0257
    environment:
      - APP_ENVIRONMENT: "staging"
      - APP_HEALTH_CHECK_URL: "https://my.staging.move.mil/health"
    steps: *deploy_app_steps

  deploy_staging_app_client_tls:
    docker:
      - image: trussworks/circleci-docker-primary:b57cdd9fd4b61d85f49134bf76c16961670f0257
    environment:
      - APP_ENVIRONMENT: "staging"
    steps: *deploy_app_client_tls_steps

  deploy_prod_migrations:
    docker:
      - image: trussworks/circleci-docker-primary:b6b61600e0a99745194eb8bfcab1c9bc1e54c28d
    environment:
      - APP_ENVIRONMENT: "prod"
    steps: *deploy_migrations_steps

  deploy_prod_app:
    docker:
      - image: trussworks/circleci-docker-primary:b6b61600e0a99745194eb8bfcab1c9bc1e54c28d
    environment:
      - APP_ENVIRONMENT: "prod"
      - APP_HEALTH_CHECK_URL: "https://my.move.mil/health"
    steps: *deploy_app_steps

  deploy_prod_app_client_tls:
    docker:
      - image: trussworks/circleci-docker-primary:b57cdd9fd4b61d85f49134bf76c16961670f0257
    environment:
      - APP_ENVIRONMENT: "prod"
    steps: *deploy_app_client_tls_steps

  integration_tests:
    docker:
      - image: trussworks/circleci-docker-primary:b6b61600e0a99745194eb8bfcab1c9bc1e54c28d
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-node-modules-cache-{{ checksum "yarn.lock" }}

      - run: make e2e_test
      - save_cache:
          key: yarn-node-modules-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: *announce_failure

  update_dependencies:
    working_directory: ~/go/src/github.com/transcom/mymove
    docker:
      - image: trussworks/circleci-docker-primary:b6b61600e0a99745194eb8bfcab1c9bc1e54c28d
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-pkg-dep-sources-{{ checksum "Gopkg.lock" }}
      - restore_cache:
          keys:
            - mymove-vendor-{{ checksum "Gopkg.lock" }}
      - run:
          name: Add ~/go/bin to path for golint
          command: echo 'export PATH=${PATH}:~/go/bin' >> $BASH_ENV
      - run: pre-commit autoupdate
      - run: make server_deps_update
      - run: make client_deps_update
      - run:
          name: Display changes
          command: |
            git --no-pager status
            git --no-pager diff --ignore-all-space --color
      - run:
          name: Push changes
          command: bin/circleci-push-dependency-updates

workflows:
  version: 2

  app:
    jobs:
      - pre_deps_golang

      - pre_deps_yarn

      - pre_test:
          requires:
            - pre_deps_golang
            - pre_deps_yarn

      #- vuln_scan # keep disabled until we work out new process
      - integration_tests
      - build_app
      - build_migrations

      - build_app:
          requires:
            - pre_deps_golang
            - pre_deps_yarn

      - build_migrations:
          requires:
            - pre_deps_golang
            - pre_deps_yarn

      - deploy_experimental_migrations:
          requires:
            - pre_test
            #- vuln_scan # keep disabled until we work out new process
            - build_app
            - build_migrations
          filters:
            branches:
              only: mk-intermediate-cert

      - deploy_experimental_app:
          requires:
            - deploy_experimental_migrations
          filters:
            branches:
              only: mk-intermediate-cert

      - deploy_experimental_app_client_tls:
          requires:
            - deploy_experimental_migrations
          filters:
            branches:
              only: mk-intermediate-cert

      - deploy_staging_migrations:
          requires:
            - pre_test
            #- vuln_scan # keep disabled until we work out new process
            - build_app
            - build_migrations
          filters:
            branches:
              only: master

      - deploy_staging_app:
          requires:
            - deploy_staging_migrations
          filters:
            branches:
              only: master

      - deploy_staging_app_client_tls:
          requires:
            - deploy_staging_migrations
          filters:
            branches:
              only: master

      - approve_prod_deploy:
          type: approval
          requires:
            - deploy_staging_app

      - deploy_prod_migrations:
          requires:
            - approve_prod_deploy
          filters:
            branches:
              only: master

      - deploy_prod_app:
          requires:
            - deploy_prod_migrations
          filters:
            branches:
              only: master

      - deploy_prod_app_client_tls:
          requires:
            - deploy_prod_migrations
          filters:
            branches:
              only: master


  dependency_updater:
    triggers:
      - schedule:
          # Monday at 4am/7am PST/EST
          cron: "0 12 * * 1"
          filters:
            branches:
              only: master
    jobs:
      - update_dependencies

experimental:
  notify:
    branches:
      only:
        - master
