development:
  dialect: "postgres"
  database: {{ env "DB_NAME" }}
  host: {{ env "DB_HOST" }}
  port: {{ env "DB_PORT" }}
  user: {{ env "DB_USER" }}
  password: {{ env "DB_PASSWORD" }}

test:
  dialect: "postgres"
  database: {{ env "DB_NAME" }}
  host: {{ env "DB_HOST" }}
  port: {{ env "DB_PORT" }}
  user: {{ env "DB_USER" }}
  password: {{ env "DB_PASSWORD" }}

container:
  dialect: "postgres"
  database: {{ env "DB_NAME" }}
  host: {{ env "DB_HOST" }}
  port: {{ env "DB_PORT" }}
  user: {{ env "DB_USER" }}
  password: {{ env "DB_PASSWORD" }}
  options:
    sslmode: "require"
