name: F/E Bundle Analysis

on:
  pull_request:
    branches: [master]

  jobs:
    build-head:
      name: 'Build head'
      runs-on: ubuntu-latest
      steps:
        - name: Check out branch
          uses: actions/checkout@v2

        - name: Set up node
          uses: actions/setup-node@v1
          with:
            node-version: '12.16.3'

        - name: Install dependencies
          run: yarn install

        - name: Build app
          run: yarn build

        - name: Build stats
          run: yarn analyze --json build/stats.json

        - name: Upload stats.json
          uses: actions/upload-artifact@v2
          with:
            name: head-stats
            path: ./build/stats.json

    build-base:
      name: 'Build base'
      runs-on: ubuntu-latest
      steps:
        - name: Check out base branch
          uses: actions/checkout@v2
          with:
            ref: ${{ github.base_ref }}

        - name: Set up node
          uses: actions/setup-node@v1
          with:
            node-version: '12.16.3'

        - name: Install dependencies
          run: yarn install

        - name: Build app
          run: yarn build

        - name: Build stats
          run: yarn analyze --json build/stats.json

        - name: Upload stats.json
          uses: actions/upload-artifact@v2
          with:
            name: base-stats
            path: ./build/stats.json

    compare:
      name: 'Compare base & head bundle size'
      runs-on: ubuntu-latest
      needs: [build-head, build-base]
      steps:
        - uses: actions/checkout@v2
        - name: Download base artifact
          uses: actions/download-artifact@v2
          with:
            name: base-stats
        - name: Download head artifact
          uses: actions/download-artifact@v2
          with:
            name: head-stats
        - name: Diff between base & head
          uses: chronotruck/webpack-stats-diff-action@1.0.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            base_stats_path: ./base-stats/stats.json
            head_stats_path: ./head-stats/stats.json
