on:
  push:
    branches: [master]

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.15'

      - name: install lint cmd
        run: go install ./cmd/ato-linter

      - name: Run custom go linter on pkg
        run: ato-linter ./pkg/...

      - name: Run custom go linter on cmd
        run: ato-linter ./cmd/...
